(defun do-parse (state inp)
  (let ((ans (funcall state (istream-read inp))))
    (cond ((typep ans 'Token) ans)
          (ans (do-parse ans (istream-next inp)))
          (T (progn (istream-next inp))
                    ans))))

(defun parse-next-token (inp)
  (assert (typep inp 'istream))
  (do-parse #'start-state inp))
